version: '3.8'

services:
  effi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: effi-backend
    expose:
      - 8000  # Gør porten synlig for andre services (ikke direkte til browser)
    volumes:
      - ./chatbot.db:/app/chatbot.db
    networks:
      - effi-network

  effi-frontend:
    image: nginx:latest
    container_name: effi-frontend
    ports:
      - "80:80"  # Browser tilgår på http://localhost
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - effi-backend
    networks:
      - effi-network

networks:
  effi-network:
    driver: bridge



